# Generated by Django 3.1.2 on 2020-10-04 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TopicComment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='topc_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Comments', to='TopicComment.topic'),
        ),
    ]
