# Generated by Django 3.1.2 on 2020-10-04 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TopicComment', '0002_auto_20201004_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='comments',
        ),
    ]
