# Generated by Django 3.1.2 on 2020-10-04 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TopicComment', '0004_auto_20201004_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='image',
        ),
    ]
