# Generated by Django 3.1.2 on 2020-10-05 10:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TopicComment', '0006_topic_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
