# Generated by Django 3.1.2 on 2020-10-05 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TopicComment', '0007_auto_20201005_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='likes',
        ),
    ]
