# Generated by Django 3.1.2 on 2020-10-06 13:31

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('TopicComment', '0015_auto_20201006_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comments',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
    ]
