# Generated by Django 3.1.2 on 2020-10-06 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TopicComment', '0020_topic_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='parent',
        ),
    ]
