# Generated by Django 3.1.2 on 2020-10-09 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TopicComment', '0022_comments_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='image',
            field=models.ImageField(null=True, upload_to='imageTopic/'),
        ),
    ]
