# Generated by Django 3.1.2 on 2020-10-08 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201008_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='profile',
            name='irst_name',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
