# Generated by Django 3.1.2 on 2020-10-08 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20201008_2322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='irst_name',
            new_name='last_name',
        ),
    ]
